// <auto-generated />
using System;
using AgendaContatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaContato.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023135901_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaContato.Domain.Models.Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContato"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("IdContato");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NomeContato")
                        .HasDatabaseName("IX_NomeContato");

                    b.ToTable("Contato", "Sistema");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("NomeGrupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo");

                    b.HasIndex("NomeGrupo")
                        .HasDatabaseName("IX_NomeGrupo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Grupo", "Sistema");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.GrupoContato", b =>
                {
                    b.Property<int>("IdGrupoContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoContato"));

                    b.Property<int>("IdContato")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("IdGrupoContato");

                    b.HasIndex("IdContato");

                    b.HasIndex("IdGrupo");

                    b.ToTable("GrupoContato", "Sistema");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Usuario_Email");

                    b.ToTable("Usuario", "Seguranca");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Usuario+UsuarioRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("UsuarioRole");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Contato", b =>
                {
                    b.HasOne("AgendaContato.Domain.Models.Usuario", "Usuario")
                        .WithMany("Contatos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Grupo", b =>
                {
                    b.HasOne("AgendaContato.Domain.Models.Usuario", "Usuario")
                        .WithMany("Grupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.GrupoContato", b =>
                {
                    b.HasOne("AgendaContato.Domain.Models.Contato", "Contato")
                        .WithMany("GrupoContatos")
                        .HasForeignKey("IdContato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaContato.Domain.Models.Grupo", "Grupo")
                        .WithMany("GrupoContatos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Usuario+UsuarioRole", b =>
                {
                    b.HasOne("AgendaContato.Domain.Models.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Contato", b =>
                {
                    b.Navigation("GrupoContatos");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Grupo", b =>
                {
                    b.Navigation("GrupoContatos");
                });

            modelBuilder.Entity("AgendaContato.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Grupos");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
